import * as maplibregl from 'https://unpkg.com/maplibre-gl@6.8.0/dist/maplibre-gl.mjs';

const events = [
  ['seoul-1392','조선 건국',1392,'한양(서울)','조선',37.5665,126.978,'politics','이성계가 조선을 건국했고, 이후 한양은 새 왕조의 수도로 정비되었다.',['태조 이성계','정도전'],['경복궁','종묘','한양도성'],[['Wikipedia · Joseon','https://en.wikipedia.org/wiki/Joseon'],['Wikidata · Joseon','https://www.wikidata.org/wiki/Q28179']]],
  ['seoul-1592','임진왜란과 한양 함락',1592,'한양(서울)','조선',37.5665,126.978,'war','일본군의 침공으로 조정은 한양을 떠났고 수도는 빠르게 점령되었다. 전쟁은 조선 전역으로 확산됐다.',['선조','이순신','도요토미 히데요시'],['경복궁','한강','평양'],[['Wikipedia · Japanese invasions of Korea','https://en.wikipedia.org/wiki/Japanese_invasions_of_Korea_(1592%E2%80%931598)']]],
  ['busan-1592','부산진 전투',1592,'부산','조선',35.1796,129.0756,'war','일본군의 조선 침공 초기에 벌어진 전투로, 부산은 전쟁의 첫 주요 접점 가운데 하나였다.',['정발','고니시 유키나가'],['부산진성','동래성'],[['Wikipedia · Siege of Busanjin','https://en.wikipedia.org/wiki/Siege_of_Busanjin']]],
  ['hansan-1592','한산도 대첩',1592,'통영 앞바다','조선',34.835,128.42,'war','이순신이 지휘한 조선 수군이 한산도 인근에서 일본 수군에 결정적 승리를 거두었다.',['이순신','와키자카 야스하루'],['한산도','통영','여수'],[['Wikipedia · Battle of Hansan Island','https://en.wikipedia.org/wiki/Battle_of_Hansan_Island']]],
  ['suwon-1796','수원화성 완공',1796,'수원','조선',37.287,127.012,'architecture','정조의 구상 아래 수원화성이 완공됐다. 정치적 이상과 당대 축성 기술이 결합된 계획도시의 핵심이었다.',['정조','정약용'],['화성행궁','장안문','팔달문'],[['Wikipedia · Hwaseong Fortress','https://en.wikipedia.org/wiki/Hwaseong_Fortress']]],
  ['london-1392','리처드 2세의 잉글랜드',1392,'런던','England',51.5072,-0.1276,'politics','리처드 2세가 잉글랜드를 통치하던 시기였다. 왕권과 귀족 세력의 긴장이 이후 더 커졌다.',['Richard II'],['Westminster','Tower of London'],[['Wikipedia · Richard II of England','https://en.wikipedia.org/wiki/Richard_II_of_England']]],
  ['beijing-1420','자금성 완공',1420,'베이징','Ming China',39.9163,116.3972,'architecture','명 영락제 시기에 자금성이 완성되고 베이징이 제국 수도로 확고히 자리잡았다.',['Yongle Emperor'],['Forbidden City','Temple of Heaven'],[['Wikipedia · Forbidden City','https://en.wikipedia.org/wiki/Forbidden_City']]],
  ['constantinople-1453','콘스탄티노폴리스 함락',1453,'콘스탄티노폴리스','Ottoman Empire',41.0082,28.9784,'war','메흐메드 2세가 이끄는 오스만군이 도시를 점령하며 비잔티움 제국이 막을 내렸다.',['Mehmed II','Constantine XI'],['Hagia Sophia','Theodosian Walls'],[['Wikipedia · Fall of Constantinople','https://en.wikipedia.org/wiki/Fall_of_Constantinople']]],
  ['venice-1271','마르코 폴로의 동방 여행 출발',1271,'베네치아','Republic of Venice',45.4408,12.3155,'exploration','마르코 폴로는 가족과 함께 아시아를 향한 긴 여정을 시작했다.',['Marco Polo','Niccolò Polo','Maffeo Polo'],['Venice','Acre'],[['Wikipedia · Marco Polo','https://en.wikipedia.org/wiki/Marco_Polo']]],
  ['xian-629','현장의 서역행 출발',629,'장안(시안)','Tang China',34.3416,108.9398,'exploration','승려 현장이 불교 경전을 구하기 위해 장안을 떠나 중앙아시아와 인도를 향했다.',['Xuanzang'],['Dunhuang','Samarkand','Nalanda'],[['Wikipedia · Xuanzang','https://en.wikipedia.org/wiki/Xuanzang']]],
  ['paris-1789','프랑스 혁명 발발',1789,'파리','France',48.8566,2.3522,'politics','바스티유 습격과 국민의회 활동을 거치며 프랑스의 정치·사회 질서가 급격히 변하기 시작했다.',['Louis XVI','Marie Antoinette'],['Bastille','Versailles'],[['Wikipedia · French Revolution','https://en.wikipedia.org/wiki/French_Revolution']]],
  ['berlin-1945','베를린 전투',1945,'베를린','Germany',52.52,13.405,'war','유럽 전선의 마지막 대규모 전투 중 하나로, 나치 독일의 붕괴와 전쟁 종결로 이어졌다.',['Georgy Zhukov','Adolf Hitler'],['Reichstag','Brandenburg Gate'],[['Wikipedia · Battle of Berlin','https://en.wikipedia.org/wiki/Battle_of_Berlin']]]
].map(([id,title,year,place,country,lat,lon,category,summary,people,relatedPlaces,sources])=>({id,title,year,place,country,lat,lon,category,summary,people,relatedPlaces,sources}));

const routes = [
  {id:'marco-polo',title:'Marco Polo',subtitle:'1271–1295 · 베네치아에서 원나라까지',icon:'🧭',person:'Marco Polo',stops:[['Venice',1271,45.4408,12.3155,'동방으로 출발'],['Acre',1271,32.9234,35.0718,'동지중해를 거쳐 내륙으로'],['Persia',1272,32.4279,53.688,'페르시아 지역 횡단'],['Central Asia',1273,40,70,'실크로드의 오아시스 도시들'],['Shangdu',1275,42.35,116.18,'쿠빌라이 칸의 궁정에 도착'],['Quanzhou',1292,24.8741,118.6757,'귀환 항해의 출발점 중 하나']]},
  {id:'yi-sun-sin',title:'이순신의 1592년',subtitle:'옥포에서 한산도까지',icon:'⚓',person:'이순신',stops:[['여수',1592,34.7604,127.6622,'전라좌수영을 기반으로 출전'],['옥포',1592,34.8906,128.6915,'옥포 해전 승리'],['사천',1592,35.0038,128.0642,'거북선이 실전에 투입된 전투로 알려짐'],['한산도',1592,34.767,128.5,'한산도 대첩'],['부산포',1592,35.101,129.04,'부산포 해전']]},
  {id:'silk-road',title:'실크로드',subtitle:'장안에서 지중해까지 이어진 교역망',icon:'🐫',stops:[['Chang’an',700,34.3416,108.9398,'동아시아의 출발점'],['Dunhuang',700,40.1421,94.6619,'하서주랑의 관문'],['Kashgar',700,39.4704,75.9898,'타림분지 서쪽의 교역 중심지'],['Samarkand',700,39.6542,66.9597,'소그드 상인의 핵심 도시'],['Constantinople',700,41.0082,28.9784,'유럽과 아시아를 잇는 거점']]}
].map(r=>({...r,stops:r.stops.map(([place,year,lat,lon,note])=>({place,year,lat,lon,note}))}));
const cities=[['Seoul','서울',37.5665,126.978],['London','런던',51.5072,-.1276],['Beijing','베이징',39.9042,116.4074],['Paris','파리',48.8566,2.3522],['Istanbul','이스탄불',41.0082,28.9784]].map(([name,label,lat,lon])=>({name,label,lat,lon}));
const labels={war:'전쟁',politics:'정치',culture:'문화',exploration:'탐험',architecture:'건축',science:'과학'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const state={mode:'explore',year:1592,selected:events.find(e=>e.id==='seoul-1592'),route:null,search:'',duelA:'Seoul',duelB:'London',favorites:JSON.parse(localStorage.getItem('tt-favorites')||'[]'),markers:[]};
const fmt=y=>`${y}년`; const safe=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const nearest=(lat,lon,year)=>[...events].sort((a,b)=>(Math.abs(a.year-year)/3+Math.hypot((a.lat-lat)*1.2,a.lon-lon))-(Math.abs(b.year-year)/3+Math.hypot((b.lat-lat)*1.2,b.lon-lon)))[0];
const visible=()=>{const q=state.search.toLowerCase().trim();const near=events.filter(e=>Math.abs(e.year-state.year)<=65);return (near.length?near:events).filter(e=>!q||`${e.title} ${e.place} ${e.people.join(' ')}`.toLowerCase().includes(q)).sort((a,b)=>Math.abs(a.year-state.year)-Math.abs(b.year-state.year));};
const showToast=(text)=>{const t=$('#toast');t.querySelector('span').textContent=text;t.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.hidden=true,2300)};

const map=new maplibregl.Map({container:'map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[45,30],zoom:1.25,minZoom:1,maxZoom:9});
map.addControl(new maplibregl.NavigationControl(),'bottom-right');
map.on('click',e=>{const hit=nearest(e.lngLat.lat,e.lngLat.lng,state.year);state.selected=hit;state.year=hit.year;state.route=null;state.mode='explore';showToast(`${hit.place} 주변에서 ${fmt(hit.year)}의 사건을 찾았습니다.`);render(true)});

function clearMarkers(){state.markers.forEach(m=>m.remove());state.markers=[]}
function renderMarkers(fly=false){clearMarkers();const list=state.mode==='duel'?[duelEvent(state.duelA),duelEvent(state.duelB)]:visible();list.forEach(e=>{const el=document.createElement('button');el.className=`map-marker ${state.selected?.id===e.id&&state.mode==='explore'?'is-selected':''}`;el.ariaLabel=`${e.place}: ${e.title}`;el.onclick=ev=>{ev.stopPropagation();state.selected=e;state.year=e.year;state.mode='explore';state.route=null;render(true)};state.markers.push(new maplibregl.Marker({element:el}).setLngLat([e.lon,e.lat]).addTo(map))});
 if(state.route){const bounds=new maplibregl.LngLatBounds();state.route.stops.forEach((s,i)=>{const el=document.createElement('div');el.className='route-marker';el.textContent=i+1;el.title=`${s.place} · ${s.year}`;state.markers.push(new maplibregl.Marker({element:el}).setLngLat([s.lon,s.lat]).addTo(map));bounds.extend([s.lon,s.lat])});map.fitBounds(bounds,{padding:80,duration:850,maxZoom:4})}
 else if(fly&&state.selected&&state.mode==='explore')map.flyTo({center:[state.selected.lon,state.selected.lat],zoom:5,duration:700});
}
function duelEvent(name){const c=cities.find(x=>x.name===name);return nearest(c.lat,c.lon,state.year)}

function renderSidebar(){let html='';if(state.mode==='explore'){const list=visible();html=`<div class="section-title"><span>이 시기의 사건</span><span>${list.length}</span></div><div class="event-list">${list.length?list.slice(0,7).map(e=>`<button class="event-row ${state.selected.id===e.id?'active':''}" data-event="${e.id}"><span class="event-dot ${e.category}"></span><span class="event-copy"><b>${safe(e.title)}</b><small>${safe(e.place)} · ${fmt(e.year)}</small></span><span>›</span></button>`).join(''):'<div class="empty">검색 결과가 없습니다. 다른 장소나 인물을 입력해 보세요.</div>'}</div>`}
 if(state.mode==='stories'){html=`<div class="section-title"><span>추천 Story Packs</span><span>${routes.length}</span></div><div class="story-list">${routes.map(r=>`<button class="story-card ${state.route?.id===r.id?'active':''}" data-route="${r.id}"><span class="story-icon">${r.icon}</span><span><b>${safe(r.title)}</b><small>${safe(r.subtitle)}</small></span><span>›</span></button>`).join('')}</div>`}
 if(state.mode==='duel'){html=`<div class="duel-controls"><div><label>장소 A</label><select id="duelA">${cities.map(c=>`<option value="${c.name}" ${c.name===state.duelA?'selected':''}>${c.label}</option>`).join('')}</select></div><div class="vs-chip">VS</div><div><label>장소 B</label><select id="duelB">${cities.map(c=>`<option value="${c.name}" ${c.name===state.duelB?'selected':''}>${c.label}</option>`).join('')}</select></div></div>`}
 $('#sidebarContent').innerHTML=html;
 $$('[data-event]').forEach(b=>b.onclick=()=>{state.selected=events.find(e=>e.id===b.dataset.event);state.year=state.selected.year;render(true)});
 $$('[data-route]').forEach(b=>b.onclick=()=>{state.route=routes.find(r=>r.id===b.dataset.route);state.year=state.route.stops[0].year;render()});
 if($('#duelA'))$('#duelA').onchange=e=>{state.duelA=e.target.value;render()}; if($('#duelB'))$('#duelB').onchange=e=>{state.duelB=e.target.value;render()};
}
function renderDetail(){const p=$('#detailPanel');if(state.mode==='duel'){const pair=[[cities.find(c=>c.name===state.duelA),duelEvent(state.duelA)],[cities.find(c=>c.name===state.duelB),duelEvent(state.duelB)]];p.innerHTML=`<div class="duel-view"><div class="panel-kicker">TIME DUEL · ${fmt(state.year)}</div><h2>같은 해, 다른 세계</h2><p>선택한 두 장소에서 현재 연도와 가장 가까운 역사 사건을 나란히 봅니다.</p>${pair.map(([c,e],i)=>`<article class="duel-card"><div class="duel-number">0${i+1}</div><small>${c.label}</small><h3>${safe(e.title)}</h3><strong>${fmt(e.year)}</strong><p>${safe(e.summary)}</p><a href="${e.sources[0][1]}" target="_blank" rel="noreferrer">원문 보기 ↗</a></article>`).join('')}</div>`;return}
 if(state.route){p.innerHTML=`<div class="route-view"><div class="panel-kicker">FOLLOW A ${state.route.person?'PERSON':'ROUTE'}</div><h2>${safe(state.route.title)}</h2><p>${safe(state.route.subtitle)}</p><div class="route-stops">${state.route.stops.map((s,i)=>`<button class="route-stop" data-stop="${i}"><span>${i+1}</span><div><b>${safe(s.place)}</b><small>${fmt(s.year)} · ${safe(s.note)}</small></div></button>`).join('')}</div></div>`;$$('[data-stop]').forEach(b=>b.onclick=()=>{const s=state.route.stops[+b.dataset.stop];state.year=s.year;map.flyTo({center:[s.lon,s.lat],zoom:5,duration:700});updateTimeline()});return}
 const e=state.selected;const fav=state.favorites.includes(e.id);p.innerHTML=`<div class="detail-hero"><div><span class="category-pill">${labels[e.category]}</span><div class="panel-kicker">${safe(e.place)} · ${fmt(e.year)}</div><h2>${safe(e.title)}</h2></div><button class="favorite ${fav?'active':''}" id="favBtn" aria-label="즐겨찾기">${fav?'♥':'♡'}</button></div><p class="summary">${safe(e.summary)}</p><div class="fact-grid"><div><small>관련 인물</small><p>${e.people.map(safe).join(' · ')}</p></div><div><small>관련 장소</small><p>${e.relatedPlaces.map(safe).join(' · ')}</p></div></div><div class="source-section"><div class="section-title"><span>확인 가능한 Source</span></div>${e.sources.map(s=>`<a class="source-link" href="${s[1]}" target="_blank" rel="noreferrer"><span>▣ ${safe(s[0])}</span><span>↗</span></a>`).join('')}</div><button class="primary-cta" id="agoBtn">⌁ What happened here 500 years ago?</button>`;
 $('#favBtn').onclick=()=>{state.favorites=fav?state.favorites.filter(id=>id!==e.id):[...state.favorites,e.id];localStorage.setItem('tt-favorites',JSON.stringify(state.favorites));renderDetail()};
 $('#agoBtn').onclick=()=>{const target=Math.max(500,state.year-500);state.year=target;const hit=nearest(e.lat,e.lon,target);state.selected=hit;showToast(`${safe(e.place)} 기준 약 500년 전으로 이동했습니다.`);render(true)};
}
function updateTimeline(){ $('#yearSlider').value=state.year;$('#yearLabel').textContent=fmt(state.year);$('#yearSubtitle').textContent=state.year===1592?'조선 · 임진왜란 원년':'시간축을 움직여 보세요'}
function render(fly=false){$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('#searchInput').value=state.search;updateTimeline();renderSidebar();renderDetail();renderMarkers(fly)}

$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.route=null;render()});
$('#homeBtn').onclick=()=>{state.mode='explore';state.route=null;render()};
$('#searchInput').oninput=e=>{state.search=e.target.value;renderSidebar();renderMarkers()};
$('#yearSlider').oninput=e=>{state.year=+e.target.value;state.route=null;updateTimeline();renderSidebar();renderDetail();renderMarkers()};
$('#themeBtn').onclick=()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('tt-theme',next);$('#themeBtn').textContent=next==='dark'?'☀':'☾'};
$('#toast button').onclick=()=>$('#toast').hidden=true;
const savedTheme=localStorage.getItem('tt-theme')||'dark';document.documentElement.dataset.theme=savedTheme;$('#themeBtn').textContent=savedTheme==='dark'?'☀':'☾';render();
